-- CREATE A DATABASE NAMED CPETE401 AND USE THE DB

SHOW DATABASES;
CREATE DATABASE CPETE401;
USE CPETE401

-- CREATE TABLE STUDENTS THAT HAS LAST NAME AND FIRST NAME
-- USING VARCHAR(100) FOR EACH ATTRIBUTE

-- VERIFY THE DEFINITION OF THE TABLE

 CREATE TABL STUDENTS
  ( LNAME VARCHAR(100))



